"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: 16194ccc7e82
Revises: a0053959c5d0
Create Date: 2020-05-26 01:17:01.921718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16194ccc7e82'
down_revision = 'a0053959c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateAdded', sa.DateTime(timezone=True), nullable=False))
    op.add_column('grades', sa.Column('dateUpdate', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('grades', 'dateAddedA')
    op.drop_column('grades', 'dateUpdateA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateUpdateA', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('dateAddedA', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('grades', 'dateUpdate')
    op.drop_column('grades', 'dateAdded')
    # ### end Alembic commands ###
