"""Added new class that keeps track of the mean of the student. It is the mean over all grades, not only one course. Also changed a spelling mistake in the overallMeans table.

Revision ID: 19dd2e0ceb93
Revises: dc68835c3e22
Create Date: 2020-05-26 23:10:16.272928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19dd2e0ceb93'
down_revision = 'dc68835c3e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overallMeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('typeID', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['typeID'], ['testTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentMeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('overalMeans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overalMeans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"overalMeans_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('studentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], name='overalMeans_studentID_fkey'),
    sa.ForeignKeyConstraint(['typeID'], ['testTypes.id'], name='overalMeans_typeID_fkey'),
    sa.PrimaryKeyConstraint('id', name='overalMeans_pkey')
    )
    op.drop_table('studentMeans')
    op.drop_table('overallMeans')
    # ### end Alembic commands ###
