"""Changed type of name in Course from Integer to String.

Revision ID: 1a164890a629
Revises: ad95fdb68ab7
Create Date: 2020-05-22 01:19:05.666732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a164890a629'
down_revision = 'ad95fdb68ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('courses_name2_key', 'courses', type_='unique')
    op.create_unique_constraint(None, 'courses', ['name'])
    op.drop_column('courses', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='unique')
    op.create_unique_constraint('courses_name2_key', 'courses', ['name2'])
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###
