"""Added two more columns to the Family class to track who submitted the request of the relation.

Revision ID: 6ccfb4e28c2d
Revises: b36ca4169556
Create Date: 2020-05-25 21:46:57.264401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccfb4e28c2d'
down_revision = 'b36ca4169556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('parentSubmit', sa.Boolean(), nullable=True))
    op.add_column('families', sa.Column('studentSubmit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'studentSubmit')
    op.drop_column('families', 'parentSubmit')
    # ### end Alembic commands ###
