"""Changed dateAdded to date in the Grade class.

Revision ID: 6fdcbef6aff4
Revises: 1ec35986eb31
Create Date: 2020-05-27 03:27:39.292031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fdcbef6aff4'
down_revision = '1ec35986eb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('grades', 'dateAdded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateAdded', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###
