"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: 73d23f41b65b
Revises: 6ccfb4e28c2d
Create Date: 2020-05-26 01:15:00.400290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d23f41b65b'
down_revision = '6ccfb4e28c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateAddedA', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'dateAddedA')
    # ### end Alembic commands ###
