"""Changed uniqueness of day in GroupTime class.

Revision ID: 7d0d914188c1
Revises: 7d35c2fe4071
Create Date: 2020-05-21 00:19:37.147729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0d914188c1'
down_revision = '7d35c2fe4071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groupTimes_day_key', 'groupTimes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('groupTimes_day_key', 'groupTimes', ['day'])
    # ### end Alembic commands ###
