"""Added all tables from preliminary datadesign as found on DESIGN.md in the git repo.

Revision ID: 7d35c2fe4071
Revises: d15637972d05
Create Date: 2020-05-20 16:42:09.843145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d35c2fe4071'
down_revision = 'd15637972d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupTimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day')
    )
    op.create_table('testTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parentID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentAbsences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('absent', sa.Boolean(), nullable=False),
    sa.Column('permitted', sa.Boolean(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentGroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groupTimes.id'], ),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('typeID', sa.Integer(), nullable=False),
    sa.Column('dateAdded', sa.Date(), nullable=False),
    sa.Column('dateUpdates', sa.Date(), nullable=False),
    sa.Column('dateTest', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['courseID'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['typeID'], ['testTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('studentGroups')
    op.drop_table('studentAbsences')
    op.drop_table('families')
    op.drop_table('courses')
    op.drop_table('testTypes')
    op.drop_table('groupTimes')
    # ### end Alembic commands ###
