"""Deleted student mean, I gave up on it.

Revision ID: 88d80d3a813c
Revises: 279a6e5fb69b
Create Date: 2020-05-27 20:47:33.935156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d80d3a813c'
down_revision = '279a6e5fb69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentMeans')
    op.add_column('users', sa.Column('mean', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mean')
    op.create_table('studentMeans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"studentMeans_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('studentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gradeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gradeID'], ['grades.id'], name='studentMeans_gradeID_fkey'),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], name='studentMeans_studentID_fkey'),
    sa.PrimaryKeyConstraint('id', name='studentMeans_pkey')
    )
    # ### end Alembic commands ###
