"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: 8e73c3f547ab
Revises: f3a7236a95d8
Create Date: 2020-05-26 02:11:15.786741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e73c3f547ab'
down_revision = 'f3a7236a95d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overalMeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overalMeans')
    # ### end Alembic commands ###
