"""Changed type of name in Course from Integer to String.

Revision ID: 92616a711c9a
Revises: 7d0d914188c1
Create Date: 2020-05-22 01:17:58.421934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92616a711c9a'
down_revision = '7d0d914188c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name2', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'courses', ['name2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'name2')
    # ### end Alembic commands ###
