"""Added a grade FK to all mean tables, and also gave them more proper names.

Revision ID: 95cdc5637b13
Revises: 19dd2e0ceb93
Create Date: 2020-05-27 03:02:11.782125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cdc5637b13'
down_revision = '19dd2e0ceb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('means', sa.Column('gradeID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'means', 'grades', ['gradeID'], ['id'])
    op.add_column('overallMeans', sa.Column('gradeID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'overallMeans', 'grades', ['gradeID'], ['id'])
    op.add_column('studentMeans', sa.Column('gradeID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'studentMeans', 'grades', ['gradeID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentMeans', type_='foreignkey')
    op.drop_column('studentMeans', 'gradeID')
    op.drop_constraint(None, 'overallMeans', type_='foreignkey')
    op.drop_column('overallMeans', 'gradeID')
    op.drop_constraint(None, 'means', type_='foreignkey')
    op.drop_column('means', 'gradeID')
    # ### end Alembic commands ###
