"""Changed table name overallMean to typeMean.

Revision ID: 9f01e72f64fd
Revises: 95cdc5637b13
Create Date: 2020-05-27 03:05:32.648826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f01e72f64fd'
down_revision = '95cdc5637b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typeMeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gradeID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('typeID', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gradeID'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['typeID'], ['testTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('overallMeans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overallMeans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"overallMeans_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('studentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gradeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gradeID'], ['grades.id'], name='overallMeans_gradeID_fkey'),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], name='overallMeans_studentID_fkey'),
    sa.ForeignKeyConstraint(['typeID'], ['testTypes.id'], name='overallMeans_typeID_fkey'),
    sa.PrimaryKeyConstraint('id', name='overallMeans_pkey')
    )
    op.drop_table('typeMeans')
    # ### end Alembic commands ###
