"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: a0053959c5d0
Revises: 73d23f41b65b
Create Date: 2020-05-26 01:16:18.969352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0053959c5d0'
down_revision = '73d23f41b65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateUpdateA', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('grades', 'dateUpdate')
    op.drop_column('grades', 'dateAdded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateAdded', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('grades', sa.Column('dateUpdate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('grades', 'dateUpdateA')
    # ### end Alembic commands ###
