"""Changed type of name in Course from Integer to String.

Revision ID: ad95fdb68ab7
Revises: 92616a711c9a
Create Date: 2020-05-22 01:18:42.751446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad95fdb68ab7'
down_revision = '92616a711c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_name_key', 'courses', type_='unique')
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('courses_name_key', 'courses', ['name'])
    # ### end Alembic commands ###
