"""Added a pending option to the Family class.

Revision ID: b36ca4169556
Revises: fe74895c8dde
Create Date: 2020-05-25 16:54:03.978390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36ca4169556'
down_revision = 'fe74895c8dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'pending')
    # ### end Alembic commands ###
