"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: bc75dcda894a
Revises: 5c85e319ea9d
Create Date: 2020-05-26 01:22:07.587188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc75dcda894a'
down_revision = '5c85e319ea9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('means', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('means', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
