"""Initial migration.

Revision ID: d15637972d05
Revises: 
Create Date: 2020-05-19 12:47:57.119526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15637972d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schoolLevels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schoolYears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('student', sa.Boolean(), nullable=False),
    sa.Column('parent', sa.Boolean(), nullable=False),
    sa.Column('tutor', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('schoolID', sa.Integer(), nullable=True),
    sa.Column('levelID', sa.Integer(), nullable=True),
    sa.Column('yearID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['levelID'], ['schoolLevels.id'], ),
    sa.ForeignKeyConstraint(['schoolID'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['yearID'], ['schoolYears.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('schools')
    op.drop_table('schoolYears')
    op.drop_table('schoolLevels')
    # ### end Alembic commands ###
