"""Removed mean column from users and also changed name of means table to courseMeans

Revision ID: df31d9ae6b6a
Revises: 88d80d3a813c
Create Date: 2020-05-27 20:56:36.114586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df31d9ae6b6a'
down_revision = '88d80d3a813c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseMeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gradeID', sa.Integer(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['courseID'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['gradeID'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('means')
    op.drop_column('users', 'mean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('means',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courseID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gradeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseID'], ['courses.id'], name='means_courseID_fkey'),
    sa.ForeignKeyConstraint(['gradeID'], ['grades.id'], name='means_gradeID_fkey'),
    sa.PrimaryKeyConstraint('id', name='means_pkey')
    )
    op.drop_table('courseMeans')
    # ### end Alembic commands ###
