"""Changed the name property in Course such that it need to be unique.

Revision ID: fe74895c8dde
Revises: 2ecd042dca4e
Create Date: 2020-05-25 16:38:08.440993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe74895c8dde'
down_revision = '2ecd042dca4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_name_key', 'courses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('courses_name_key', 'courses', ['name'])
    # ### end Alembic commands ###
