"""Removed date column from all mean tables.

Revision ID: 1ec35986eb31
Revises: 9f01e72f64fd
Create Date: 2020-05-27 03:20:28.418256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ec35986eb31'
down_revision = '9f01e72f64fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('means', 'date')
    op.drop_column('studentMeans', 'date')
    op.drop_column('typeMeans', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typeMeans', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('studentMeans', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('means', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
