"""Removed FK gradeID from typeMean, since only the last calculated means are of interest.

Revision ID: 279a6e5fb69b
Revises: 6fdcbef6aff4
Create Date: 2020-05-27 16:19:45.011164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279a6e5fb69b'
down_revision = '6fdcbef6aff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('typeMeans_gradeID_fkey', 'typeMeans', type_='foreignkey')
    op.drop_column('typeMeans', 'gradeID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typeMeans', sa.Column('gradeID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('typeMeans_gradeID_fkey', 'typeMeans', 'grades', ['gradeID'], ['id'])
    # ### end Alembic commands ###
