"""Deleted the StudentAbsences class as I eventually did not follow through with actually using this class.

Revision ID: 4f9882076f78
Revises: df31d9ae6b6a
Create Date: 2020-06-01 02:59:20.571542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9882076f78'
down_revision = 'df31d9ae6b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentAbsences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentAbsences',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"studentAbsences_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('studentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('absent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('permitted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('late', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['users.id'], name='studentAbsences_studentID_fkey'),
    sa.PrimaryKeyConstraint('id', name='studentAbsences_pkey')
    )
    # ### end Alembic commands ###
