"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: 5c85e319ea9d
Revises: 16194ccc7e82
Create Date: 2020-05-26 01:20:44.745149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c85e319ea9d'
down_revision = '16194ccc7e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('means', sa.Column('dateA', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('means', 'dateA')
    # ### end Alembic commands ###
