"""Changed naming from dateUpdates to dateUpdate in Grade class.

Revision ID: c87934d760a4
Revises: 1a164890a629
Create Date: 2020-05-22 02:20:28.441170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87934d760a4'
down_revision = '1a164890a629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateUpdate', sa.Date(), nullable=False))
    op.drop_column('grades', 'dateUpdates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('dateUpdates', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('grades', 'dateUpdate')
    # ### end Alembic commands ###
