"""Added a table for overall means.

Revision ID: dc68835c3e22
Revises: 8e73c3f547ab
Create Date: 2020-05-26 04:51:51.092964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc68835c3e22'
down_revision = '8e73c3f547ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overalMeans', sa.Column('studentID', sa.Integer(), nullable=False))
    op.add_column('overalMeans', sa.Column('typeID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'overalMeans', 'testTypes', ['typeID'], ['id'])
    op.create_foreign_key(None, 'overalMeans', 'users', ['studentID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overalMeans', type_='foreignkey')
    op.drop_constraint(None, 'overalMeans', type_='foreignkey')
    op.drop_column('overalMeans', 'typeID')
    op.drop_column('overalMeans', 'studentID')
    # ### end Alembic commands ###
