"""Changed the date in mean and the dateAdded and dateUpdate to dateTime columns.

Revision ID: f3a7236a95d8
Revises: bc75dcda894a
Create Date: 2020-05-26 01:23:05.330779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3a7236a95d8'
down_revision = 'bc75dcda894a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('means', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('means', 'dateA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('means', sa.Column('dateA', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('means', 'date')
    # ### end Alembic commands ###
